---
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: relayname
    metrics_path: /metrics
    static_configs:
      - targets: ['relay-ip:9100']
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)
        target_label: instance
        replacement: anzeigename
    basic_auth:
      username: 
      password: 

  - job_name: relayname
    metrics_path: /metrics
    static_configs:
      - targets: ['relay-ip:9035']
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)
        target_label: instance
        replacement: anzeigename
    basic_auth:
      username: 
      password: 
